app/urls.py
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views as v


urlpatterns = [
    # path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    # path('users/', include('django.contrib.auth.urls')),

    # path('login/', login, name='login'),
    # path('logout/', logout, name='logout'),
    # path('auth/', include('social_django.urls', namespace='social')),


    path('', v.home, name='home'),
    path('discover/', v.discover, name='discover'),
    # path('library/', v.library, name='library'),
    # path('searched/', v.BrandListView.as_view()),
    # path('db_update/<category>/', v.db_update),
    path('rating/', v.RatingView.as_view(), name='rating'),
    path('myfavorite/', v.myfavorite, name='myfavorite'),
    path('brands/<bname>/', v.brand_detail, name='brand_detail'),
    path('brands/<bname>/identity/', v.identity, name='identity'),
    # path('brand/<brand_name>/interest/trend/', interest_trend, name='interest_trend'),
    path('brands/<brand_name>/gtrend/', v.gtrend, name='gtrend'),
    path('search_helper/', v.search_helper, name='search_helper'),
    # path('bnames/', v.bnames, name='bnames'),
    #path('brands/<bname>/identities/', identities, name='identities'),

    path('journey/<str:words>/', v.journey, name='journey'),
    path('feed/<int:pk>/', v.feed, name='feed'),
    path('channels/', v.channels, name='channels'),
    path('channel/<str:chname>/', v.channel, name='channel'),
    # path('feed_blocks/<str:keywords>/', v.feed_blocks, name='feed_blocks'),
    # path('feed_block/<int:feed_id>/', v.feed_block, name='feed_block'),

    path('me/', v.me, name='me'),

    path('profiling/', v.profiling, name='profiling'),
    path('save_worldcup/', v.SaveWorldcupView.as_view(), name='save_worldcup'),
    # path('save_like/', v.SaveLikeView.as_view(), name='save_like'),

    path('level_test/', v.level_test, name='level_test'),
    path('update_likes/', v.UpdateLikesView.as_view(), name='update_likes'),
    path('update_myfavorite/', v.UpdateMyfavoriteView.as_view(), name='update_myfavorite'),
    path('actions/', v.ActionsView.as_view(), name='actions'),

    path('posts/', v.posts, name='posts'),
    # path('posts/sub/', v.posts_sub, name='posts_sub'),
    path('posts/newpost/', v.newpost, name='newpost'),
    path('posts/<int:pk>/', v.post_detail, name='post_detail'),
    path('posts/<int:pk>/edit/', v.editpost, name='editpost'),
    path('posts/<int:pk>/delete/', v.deletepost, name='deletepost'),
    path('posts/<int:pk>/commenting/', v.commenting_post, name='commenting_post'),
    path('commentpost_actions/', v.CommentPostActionsView.as_view(), name='commentpost_actions'),

    path('blocks/', v.blocks, name='blocks'),
    # path('search/<qry>/', v.search, name='search'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')), 

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
# from django.core.urlresolvers import reverse_lazy
import json
import requests
import numpy as np
from collections import OrderedDict
from custom_user.models import AbstractEmailUser

from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType

# Create your models here.


class Option(models.Model):
    idwords_default = [
        {"럭셔리": "럭셔리 고급 호화 과시 명품 luxury 비싼 고가 expensive pricy pricey",
         "캐주얼": "캐주얼 캐쥬얼 casual 스타일리시 스타일리쉬 stylish"},
        {"유니크": "유니크 독특 독창 unique 개성 only 참신 신선 특이 아이디어 철학",
         "대중성": "대중 popular 널리 흔한 massive mass 대중성"},
        {"정통성": "정통 클래식 classic 품격 약속 신뢰 믿음 예측 견고 품질 안정",
         "트렌디": "트렌디 트랜디 트렌드 트랜드 유행 trend trendy 변화 새로운 민감 예민 신상 최신"},
        {"포멀": "포멀 formal 노멀 normal 평범 일상 무난 기본 베이스 베이직 base basic",
         "액티브": "화제 인기 hot 튀는 액티브 active 앞서가는 실험 과감 선도 선구 대담"}
    ]

    optname = models.CharField(max_length=120, default='init')
    idwords = models.TextField(default=json.dumps(idwords_default, ensure_ascii=False))
    api = models.CharField(max_length=120, default='http://127.0.0.1:8080/api')
    id_scaletype = models.IntegerField(default='0')

    def __str__(self):
        return self.optname


class BigIdAbstract(models.Model):
    id = models.BigAutoField(primary_key=True)

    class Meta:
        abstract = True


class CustomEmailUser(AbstractEmailUser, BigIdAbstract):
    pass


class Hashtag(BigIdAbstract):
    hashtag = models.CharField(max_length=120)
    def __str__(self):
        return self.hashtag


class Post(BigIdAbstract):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts/%Y/%m/%d/origin')
    content = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    brands_related = models.ManyToManyField('Brand', blank=True)

    def __str__(self):
        return '{created_at} {email}'.format(created_at=self.created_at, email=self.user.email)

    def get_absolute_url(self):
        url = reverse_lazy('post_detail', kwargs={'pk':self.pk})
        return url


class CommentBrand(BigIdAbstract):
    brand = models.ForeignKey('Brand', blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{created_at} {email}'.format(created_at=self.created_at, email=self.user.email)


class CommentPost(BigIdAbstract):
    post = models.ForeignKey(Post, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{created_at} {email}'.format(created_at=self.created_at, email=self.post.user.email)

    def get_absolute_url(self):
        url = reverse_lazy('post_detail', kwargs={'pk':self.post.pk})
        return url


class Channel(models.Model):
    limit = models.Q(app_label='app', model='brand') | models.Q(app_label='app', model='customchannel')
    content_type = models.ForeignKey(ContentType, limit_choices_to=limit, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content = GenericForeignKey('content_type', 'object_id')
    master = models.ForeignKey('Profile', blank=True, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    nlikes = models.IntegerField(default='0')

    def __str__(self):
        return str(self.content)
        # return str(self.created_at)

    def feeds(self):
        return self.feed_set.all().prefetch_related('hashtags').select_related('author').order_by('-timestamp')


class Customchannel(models.Model):
    name = models.CharField(max_length=120)
    keywords = models.TextField(max_length=500, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to='customchannel_images', default='') # 로고는 필수 (null=True 하면 안됨)

    channels = GenericRelation(Channel, related_query_name='channel')

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=120)
    fullname_kr = models.CharField(max_length=120, blank=True, null=True)
    fullname_en = models.CharField(max_length=120, blank=True, null=True)
    keywords = models.TextField(max_length=500, blank=True, null=True)
    # website = models.CharField(max_length=200, blank=True, null=True)
    origin = models.CharField(max_length=50, blank=True, null=True)
    awareness = models.FloatField(default=0)
    category = models.CharField(max_length=120, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    # history = models.TextField(default='', blank=True, null=True)
    image = models.ImageField(upload_to='brand_images', default='') # 로고는 필수 (null=True 하면 안됨)

    channels = GenericRelation(Channel, related_query_name='channel')

    def __str__(self):
        return self.fullname_en.capitalize()


class Profile(BigIdAbstract):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(default='', max_length=500)

    worldcup = models.TextField(blank=True, null=True, default='{}')
    initial_awared = models.TextField(blank=True, null=True)
    # awareness = models.TextField(blank=True, null=True, default='{}')

    brand_likes = models.ManyToManyField(Brand, blank=True, related_name='brand_likes_set')
    post_likes = models.ManyToManyField(Post, blank=True, related_name='post_likes_set')
    brand_bookmarks = models.ManyToManyField(Brand, blank=True, related_name='brand_bookmarks_set')
    post_bookmarks = models.ManyToManyField(Post, blank=True, related_name='post_bookmarks_set')

    myfavorite = models.ForeignKey(Brand, blank=True, null=True, on_delete=models.SET_NULL, related_name='myfavorite_set')
    level_tested = models.ManyToManyField(Brand, blank=True, related_name='leveltested_set')

    def __str__(self):
        return self.user.email

    def update_actions(self, action, add=None, remove=None):
        if action=='brand_like':
            pool = self.brand_likes
            obj = Brand.objects

        elif action=='brand_bookmark':
            pool = self.brand_bookmarks
            obj = Brand.objects

        elif action=='post_like':
            pool = self.post_likes
            obj = Post.objects

        elif action=='post_bookmark':
            pool = self.post_bookmarks
            obj = Post.objects

        if (add is not None) and (remove is None):
            pool.add(obj.get(pk=add))

        elif (add is None) and (remove is not None):
            pool.remove(obj.get(pk=remove))

    def get_actions(self, action, pk=None):
        if action=='brand_like':
            actions = self.brand_likes

        elif action=='brand_bookmark':
            actions = self.brand_bookmarks

        elif action=='post_like':
            actions = self.post_likes

        elif action=='post_bookmark':
            actions = self.post_bookmarks

        if pk is None:
            return actions.all()

        else:
            return actions.get(pk=pk)

    def like_this(self, obj):
        type = obj.__class__.__name__.lower()
        action = type + '_like'
        return self.get_actions(action, pk=obj.pk) is not None

    def bookmark_this(self, obj):
        type = obj.__class__.__name__.lower()
        action = type + '_bookmark'
        return self.get_actions(action, pk=obj.pk) is not None

    def get_likes(self, type):
        if type=='brand':
            return self.brand_likes.all()

        elif type=='post':
            return self.post_likes.all()

    def get_worldcupped(self):
        worldcupped = []
        for bnames in json.loads(self.worldcup).keys():
            worldcupped += bnames.split('-')
        return set(worldcupped)


    def get_awared(self):
        # _likes = self.get_likes()
        _likes = self.get_likes('brand').values_list('name', flat=True)
        _worldcupped = self.get_worldcupped()
        awared = set(_likes) | _worldcupped
        return awared

    def awareness(self):
        awared = self.get_awared()
        brands = Brand.objects.all()
        bawareness = set(brands.values_list('awareness', flat=True))

        my_awareness = OrderedDict()
        for _baware in bawareness:
            _brands = brands.filter(awareness=_baware)
            _brands_awared = _brands.filter(name__in=awared)
            my_awareness[int(_baware)] = len(_brands_awared)/len(_brands)
            # my_awareness[int(_baware)] = '{}%'.format(round(len(_brands_awared)/len(_brands) * 100))

        # print(my_awareness)
        return my_awareness


    def _weighting(self, like=1, morelike=1):
        weights = {}
        likes = self.get_likes('brand').values_list('name', flat=True)
        for pair,selected in json.loads(self.worldcup).items():
            for b in pair.split('-'):
                add = 1
                if b==selected: add += like
                if b in likes: add += morelike
                # if b in self.get_likes(): add += morelike
                weights[b] = weights[b] + add if b in weights else add
        return weights


    def weights(self, like=1, morelike=1):
        w = self._weighting(like=like, morelike=morelike)
        w_sum = sum(w.values())
        return {k:v/w_sum for k,v in w.items()}


    def identify(self, idty_all, like=1, morelike=1):
        score = {}
        weights = self._weighting(like=like, morelike=morelike)

app/templates/app/action_icon.html
{% load ctags %}

{% if action_type == 'like' %}
  {% if user.is_authenticated and user|like_this:obj %}
    <i class="action-icon" state="add" data-feather="heart"></i>
  {% else %}
    <i class="action-icon" state="remove" data-feather="heart"></i>
  {% endif %}

{% elif action_type == 'bookmark' %}
  {% if user.is_authenticated and user|bookmark_this:obj %}
    <i class="action-icon" state="add" data-feather="bookmark"></i>
  {% else %}
    <i class="action-icon" state="remove" data-feather="bookmark"></i>
  {% endif %}

{% elif action_type == 'collection' %}
  {% if user.is_authenticated and user|bookmark_this:obj %}
    <i class="action-icon" state="add" data-feather="folder-plus"></i>
  {% else %}
    <i class="action-icon" state="remove" data-feather="folder-plus"></i>
  {% endif %}
{% endif %}

{% if counter == 'yes' %}
  <div class="action-icon-counter">1346352000</div>
{% endif %}

app/templates/app/brand_card.html
{% if brand %}
<div class="bcard card" bname="{{ brand.name }}" href="{% url 'brand_detail' brand.name %}" onclick="bcard_click(this)" style="display:none;">

  <div class="bcard_base">
    <img class="bcard_img" src="{{ brand.logo.url }}" alt="{{ brand.name }}" style="object-fit:contain;">
    <div class="bcard_like" onclick="toggle_like(event, this)">
      {% load ctags %}
      {% if user.is_authenticated and user.email|liked:brand.name %}
        <i class="bcard_like_icon" data-feather="star" style="" state="like"></i>
      {% else %}
        <i class="bcard_like_icon" data-feather="star" style="" state="dontlike"></i>
      {% endif %}
    </div>
  </div>

  {% if type == "more" %}
  <div class="bcard_more">
    <button class="bcard_more_btn ui compact icon button" onclick="bcard_more(event, this)">
      <i class="bcard_more_icon ellipsis horizontal icon"></i>
    </button>

    <div class="bcard_cover" onclick="bcard_cover_click(event, this)" onmouseleave="bcard_cover_mouseleave(this)">
      <div class="ui centered grid">
        {% if brand.score %}
        <div class="row">
          <div class="bcard_score">
            <span class="bcard_stat_value">{{ brand.score }}</span><br>
            <span class="bcard_stat_label">유사도 %</span>
          </div>
        </div>
        {% endif %}

        <div class="row">
          <button class="ui mini compact labeled icon basic button" onclick="compare(this)">
            <i class="exchange icon"></i>
            COMPARE
          </button>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

</div>
{% endif %}


{% if post %}
<div class="bcard card" href="{% url 'post_detail' post.pk %}" onclick="bcard_click(this)" style="display:none;">
  <div class="bcard_base">
    <img class="bcard_img" src="{{ post.image.url }}" style="object-fit:cover;">
    <div class="bcard_like" onclick="toggle_like(event, this)">
      {% load ctags %}
      {% if user.is_authenticated and user.email|liked:brand.name %}
        <i class="bcard_like_icon" data-feather="star" style="" state="like"></i>
      {% else %}
        <i class="bcard_like_icon" data-feather="star" style="" state="dontlike"></i>
      {% endif %}
    </div>
  </div>
</div>
{% endif %}

app/templates/app/level_test.html
{% extends "app/layout.html" %}

{% block menu_top %}
  {% include "app/menu_top.html" with rating_act="active" %}
{% endblock menu_top %}


{% block content %}
<style>
</style>

{% load static %}
<div class="ui text container" style="text-align:center;margin-top:20px">
  <div id="level-test"></div>
</div>
{% endblock content %}


{% load static %}
{% block js %}
  {{ block.super }}
  <script type="text/javascript">
    load_blocks('#level-test', "{% url 'blocks' %}?type=leveltest");
  </script>
{% endblock js %}

app/templates/app/login.html
{% load socialaccount %}

<div class="ui login mini modal">
  <!-- <div class="ui header" style="text-align:center">
    소셜 로그인
  </div> -->

  <div class="content">
    <a class="fluid ui button" href="{% provider_login_url 'google' %}">
      구글 아이디로 로그인
    </a>
    <br>

    <a class="fluid ui green button" href="{% provider_login_url 'naver' %}">
      네이버 아이디로 로그인(X)
    </a>
    <br>

    <a class="fluid ui blue button" href="{% provider_login_url 'facebook' method='oauth2' %}">
      페이스북 아이디로 로그인
    </a>

    <!-- <a class="ui large image basic label">
      <img src="https://www.shareus.co.kr/upload/static/icon/social/naver-n-green.png">
      네이버 아이디로 로그인
    </a>
    <br> -->

    <!-- <div class="ui image button">
      <img src="https://www.shareus.co.kr/upload/static/icon/social/naver-n-green.png" style="height:50px;float:left">
      네이버 아이디로 로그인
    </div> -->

  </div>

</div>

app/templates/app/menu_top.html
{% include "app/login.html" %}
{% include "app/welcome.html" %}

<style>
  #top-shown .ui.menu a:not(.active).item:hover {
    color:#a4a4a4 !important;
  }

  .bsearch-submit:hover, #search-hider:hover, #show-library:hover {
    background: rgba(220, 220, 220, .3) !important;
  }

  #top-header {
    box-shadow: 0 0 10px rgba(0,0,0,0.2) !important;
    background: white;
    position: fixed;
    top: 0;
    width: 100%;
    height: none;
    z-index: 100;
  }

  #top-header > .background-title {
    background: none;
    position: absolute;
    width: 100%;
  }

  #top-header > .menu {
    background: none;
    width: 100%;
    position: relative;
    height: 60px;
  }

  #top-header .right.menu {
    background-image: linear-gradient(to right, rgba(255,255,255,0), rgba(255,255,255,1));
  }

  #top-header .ui.menu a.item:hover {
    color: red !important;
    /* background: rgba(255,255,255,0.7); */
  }

  #top-header .right.menu .item {
    border-radius: 20px !important;
    margin: 1px !important;
    width: 40px !important;
    height: 40px !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
    padding: 0 !important;
  }

  #top-header .right.menu .first.item {
    margin-left: 20px !important;
  }

  #top-header .right.menu .last.item {
    margin-right: 20px !important;
  }

  #top-header .right.menu .item .icon {
    position: absolute;
    width: 60%;
    height: 60%;
    top: 50%;
    left: 20px;
    transform: translate(-50%, -50%);
  }

  #top-header .profile.image {
    object-fit: cover;
    width: 30px;
    height: 30px;
  }

  @keyframes searcher_show {
    100% { bottom:0%; }
  }

  @keyframes searcher_hide {
    0% { bottom:0%; }
  }
</style>


<div id="top-header">
  <!-- <div class="background-title">
    {% include "app/title.html" with title="GET.CH." type="header" %}
  </div> -->

  <div class="ui secondary icon compact menu">
    <a class="header item" style="font-size:30px;font-weight:900;letter-spacing:-3px;padding:10px;border-radius:10px;" href="{% url 'home' %}">
      <span>GET</span><span style="color:aqua">.</span><span>CH</span>
    </a>

    <div class="right menu">
      <a class="first item">
        <i class="icon" data-feather="plus-square"></i>
      </a>

      <a class="item" id="search-shower">
        <i class="icon" data-feather="search"></i>
      </a>

      <a class="item" href="{% url 'channels' %}">
        <i class="icon" data-feather="grid"></i>
      </a>

      {% if user.is_authenticated %}
      <a class="last item {{ me_act }}" href="{% url 'me' %}">
        <img class="profile ui circular image" src="{{ user.socialaccount_set.all.0.get_avatar_url }}">
      </a>

      {% else %}
      <a class="last login item {{ me_act }}">
        <i class="icon" data-feather="user"></i>
      </a>
      {% endif %}

    </div>
  </div>

  {% include 'app/searcher.html' %}
</div>

app/templates/app/post_comment.html
<style>
  #id_comment:focus {
    background: lightyellow !important;
  }
</style>

<div class="ui header" style="background:none;">
  <div class="content">
    Comments
  </div>
</div>

<div class="ui comments" style="background:none;max-width:none;">

  {% for comment in post.commentpost_set.all %}
    <div class="comment" comment-id="{{ comment.pk }}" style="position:relative;background:none;padding:0;">
      <!-- <a class="">
        {% include "app/user_avatar.html" with user=comment.user %}
      </a> -->

      <!-- <div class="content"> -->

        <div class="text" style="background:none;margin-top:0;">
          <textarea readonly rows="1" class="other-comments" style="background:none;height:auto;width:100%;resize:none;overflow-y:hidden;border:none;padding-left:60px;padding-right:10px;padding-top:30px;padding-bottom:10px;line-height:1.3em;">{{ comment.content }}</textarea>
        </div>

        <div style="position:absolute;top:10px;left:10px;">
          {% include "app/user_avatar.html" with user=comment.user %}
        </div>

        <!-- <a class="author" style="position:absolute;top:0;">{{ comment.user.email }}</a> -->
        <div class="metadata" style="position:absolute;top:10px;left:55px;">
          <span class="date">{{ comment.created_at }}</span>
        </div>

        <div class="actions" style="position:absolute;top:10px;right:10px;">
          <a class="like"><i class="star outline icon" style="width:15px;background:none;margin:0px;"></i></a>
          <a class="reply"><i class="comment outline icon" style="width:15px;background:none;margin:0px;"></i></a>
          {% if user == comment.user %}
          <a class="edit" onclick="edit_commentpost(this)"><i class="edit outline icon" style="width:15px;background:none;margin:0px;"></i></a>
          <a class="delete" onclick="ask_delete_commentpost('{{comment.pk}}')"><i class="trash alternate outline icon" style="width:15px;background:none;margin:0px;"></i></a>
          <!-- <a class="delete" onclick="delete_commentpost('{{comment.pk}}')"><i class="trash alternate outline icon" style="width:15px;background:none;margin:0px;"></i></a> -->
          {% endif %}
        </div>
      <!-- </div> -->
    </div>
  {% endfor %}

</div>


{% if user.is_authenticated %}
<form class="ui reply form" method="post" action="{% url 'commenting_post' post.pk %}" style="background:none;">
  {% csrf_token %}
  <div class="field" style="background:none;position:relative;">
    <textarea rows="1" id="id_comment" name="content" style="resize:none;background:none;padding-left:60px;padding-right:60px;height:auto;overflow-y:hidden;border:none;min-height:50px;line-height:1.3em;" placeholder="Comment here" oninput="show_commenting(this)"></textarea>

    <div style="position:absolute;top:10px;left:10px;">
      {% include "app/user_avatar.html" with user=post.user %}
    </div>

    <!-- <button class="commenting ui compact submit icon button" onclick="return empty()" style="position:absolute;bottom:10px;right:10px;"> -->
    <button class="commenting ui compact submit icon button" style="position:absolute;bottom:10px;right:10px;background:none;opacity:0;">
      <i class="comment alternate large icon"></i>
    </button>
  </div>
</form>

{% else %}
{% endif %}


<div class="ui tiny edit_commentpost modal">
  <i class="close icon"></i>
  <div class="header">
    Edit comment
  </div>
  <div class="content">
    <form class="ui form" method="" action="">
      <div class="field">
        <label>Original comment</label>
        <textarea rows="2">NOT WORKING YET</textarea>
      </div>
    </form>
  </div>
  <div class="actions">
    <div class="ui black deny button">Cancel</div>
    <div class="ui positive right labeled icon button">
      Edit
      <i class="checkmark icon"></i>
    </div>
  </div>
</div>

<div class="ui mini delete_commentpost modal">
  <i class="close icon"></i>
  <div class="header">
    ALERT
  </div>
  <div class="content">
    <p>댓글을 지울건가요? 복구는 불가능하니, 신중히 생각해주세요.</p>
  </div>
  <div class="actions">
    <div class="ui black deny button">Cancel</div>
    <div class="ui positive right labeled icon button">
      Delete
      <i class="checkmark icon"></i>
    </div>
  </div>
</div>

<script>
  function show_commenting(textarea) {
    var commenting = $(textarea).siblings(".commenting")

    if (textarea.value.length > 0) {
      commenting.css({
        "opacity": 1,
        "transition": "opacity 1s ease"
      });
    } else {
      commenting.css({
        "opacity": 0,
        "transition": "opacity 1s ease"
      });
    }
  };

  function empty() {
    var x = document.getElementById("id_comment").value;
    if (x == "") {
      return false;
    }
  }

  $('#id_comment').each(function() {
    this.style.height = 'auto';
    this.style.height = (this.scrollHeight) + 'px';
  }).on('input', function() {
    this.style.height = 'auto';
    this.style.height = (this.scrollHeight) + 'px';
  });

  $('.other-comments').each(function() {
    this.style.height = 'auto';
    this.style.height = (this.scrollHeight) + 'px';
  });

  function edit_commentpost(edit_link) {
    $('.edit_commentpost.modal').modal('show');
    // console.log(1);
  }

  function delete_commentpost(comment_pk) {
    $('.delete_commentpost.modal')
      .modal({
        onApprove: function() {
          $.ajax({
            url: {% url 'commentpost_actions' %},
            async: true,
            type: 'GET',
            data: {
              pk: comment_pk,
              action: 'delete'
            },
            dataType: 'json',
            success: function(jqXHR) {
              if (!jqXHR.success) {
                alert("데이터를 처리하는데 문제가 발생하였습니다.");
              } else {
                var ele = ".comment[comment-id='" + comment_pk + "']"
                $(ele).remove();
              };
            }
          });
        }
      })
      .modal('show');
  }
</script>

app/templates/app/sidebar.html
<div class="item">
  <h1 class="ui inverted center aligned icon header">
    <br>
    <i class="bold icon"></i>
    <div class="content">
      B:match
      <div class="sub header">
        Discover your style with Brands<br>
      </div>
    </div>
  </h1>
</div>

<a class="item">
  <i class="info icon"></i>
  about
</a>

<a class="item">
  <i class="cog icon"></i>
  settings
</a>

app/templates/app/simblocks.html
<div>
  <h3 style="background:none">Similar</h3>
  {% include "app/baseblocks.html" with type='simbrands' blocks=sims opt='more' %}
</div>

<br><br>

<div>
  <h3 style="background:none">Different</h3>
  {% include "app/baseblocks.html" with type='simbrands' blocks=diffs opt='more' %}
</div>

app/templates/app/user_avatar.html
{% if profile %}
  {% if profile.image %}
  <img class="ui circular image" src="{{ profile.image.url }}" style="object-fit:cover;width:30px;height:30px">

  {% else %}
  <img class="ui circular image" src="{{ profile.user.socialaccount_set.all.0.get_avatar_url }}" style="object-fit:cover;width:30px;height:30px">
  {% endif %}

{% elif user %}
<img class="ui circular image" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" style="object-fit:cover;width:30px;height:30px">
{% endif %}